name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
#    defaults:
#    run:
#      shell: msys2bash.cmd {0}


    steps:
    - uses: actions/checkout@v2
      shell: msys2bash.cmd {0}
    - name: autogen.sh
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    
