name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
#    defaults:
#    run:
#      shell: msys2bash.cmd {0}


    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
    - shell: msys2 {0}
      run: ./autogen.sh
    - shell: msys2 {0}
      run: ./configure
    - shell: msys2 {0}
      run: make
    
